#!/bin/bash

# Find the DNS Name of the s3d instance
dns_name=$(
  aws ec2 describe-instances \
  | jq -r '
    .Reservations[].Instances[]
    | select(.State.Name == "running")
    | select(.Tags[0].Value == "s3d-i1")
    | .PublicDnsName
  '
)

# Set this shell output mode such that it will echo the commands of this
# script.
set -x

# Copy any JSON files that exit in root to the EC2 instance.
scp -i ~/s3d-k1.pem ~/*.json ec2-user@$dns_name:~

# Now actually start the SSH session
ssh -i ~/s3d-k1.pem ec2-user@$dns_name
